#!/bin/bash
# NEXUS — Automated Report Generator
# Outputs to Notion, Obsidian vault, and/or markdown
# Usage: bash report.sh <ip|domain> [--notion] [--obsidian] [--all]

TARGET="$1"
MODE="${2:---all}"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_DIR=~/.openclaw/nexus_cache
REPORT_DIR=~/.openclaw/nexus_reports
OBSIDIAN_VAULT="${OBSIDIAN_VAULT_PATH:-$HOME/Documents/ObsidianVault}"
NOTION_TOKEN="${NOTION_API_TOKEN}"
NOTION_DB_ID="${NOTION_DATABASE_ID}"

mkdir -p "$REPORT_DIR"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
DATE_SLUG=$(date '+%Y-%m-%d')
REPORT_SLUG="${TARGET//[.\/]/_}_${DATE_SLUG}"

if [ -z "$TARGET" ]; then
  echo "Usage: report.sh <ip|domain> [--notion|--obsidian|--all]"
  exit 1
fi

# ── Run threat score first (get fresh JSON) ────────────────────
echo "🔄 Running threat score aggregator..."
bash "$DIR/threat_score.sh" "$TARGET" --json > /tmp/nexus_score.json 2>/dev/null

SCORE=$(python3 -c "import json; print(json.load(open('/tmp/nexus_score.json'))['final_score'])" 2>/dev/null || echo 0)
RISK=$(python3 -c  "import json; print(json.load(open('/tmp/nexus_score.json'))['risk'])" 2>/dev/null || echo "UNKNOWN")

# ── Run full recon pipeline ────────────────────────────────────
echo "🔄 Running full recon pipeline..."
RECON_OUTPUT=$(bash "$DIR/recon.sh" "$TARGET" 2>&1)

# ── Build Markdown report ──────────────────────────────────────
build_markdown() {
python3 - <<EOF
import json, datetime

score_data = json.load(open('/tmp/nexus_score.json'))
score  = score_data['final_score']
risk   = score_data['risk']
target = score_data['target']
ts     = score_data['timestamp']
bd     = score_data['breakdown']

risk_emoji = {'CRITICAL':'🔴','HIGH':'🟠','MEDIUM':'🟡','LOW':'🟡','CLEAN':'🟢'}.get(risk,'⚪')
risk_bar   = '█' * int(score/10) + '░' * (10 - int(score/10))

report = f"""# NEXUS Intelligence Report
**Target:** \`{target}\`
**Generated:** {ts}
**Analyst:** NEXUS Autonomous OSINT System

---

## {risk_emoji} Threat Assessment

| Metric | Value |
|--------|-------|
| **Overall Score** | {score}/100 |
| **Risk Level** | {risk} |
| **Score Bar** | {risk_bar} |

---

## Score Breakdown

| Source | Score | Detail |
|--------|-------|--------|
"""

source_names = {
    'virustotal': '🔬 VirusTotal',
    'abuseipdb':  '🚨 AbuseIPDB',
    'shodan':     '🌐 Shodan',
    'censys':     '🔭 Censys',
    'cve':        '🛡 CVE/NVD'
}

for key, name in source_names.items():
    s = bd.get(key, {})
    sc = s.get('score', 'N/A')
    detail = s.get('detail', '')
    bar = '█' * int((int(sc) if str(sc).isdigit() else 0)/20)
    report += f"| {name} | {sc}/100 {bar} | {detail} |\n"

report += f"""
---

## Recon Data

\`\`\`
{open('/tmp/nexus_recon.txt').read() if __import__('os').path.exists('/tmp/nexus_recon.txt') else 'Run recon.sh separately for full output'}
\`\`\`

---

## Recommendations

"""

if risk in ['CRITICAL', 'HIGH']:
    report += """- ⛔ **Block immediately** — add to firewall deny list
- 🔔 Set persistent monitoring alert for this target
- 📤 Submit to AbuseIPDB if not already reported
- 🔍 Pivot OSINT: check ASN block, related IPs, registrar
"""
elif risk == 'MEDIUM':
    report += """- 👁 **Monitor closely** — elevated risk indicators present
- 🗂 Cross-reference with internal threat intel feeds
- ⏱ Re-scan in 7 days for trend analysis
"""
else:
    report += """- ✅ No immediate action required
- 📅 Scheduled re-scan recommended in 30 days
"""

report += f"""
---

## Tags

#nexus #osint #threat-intel #{risk.lower()} #{target.replace('.', '-')}

---
*Report generated by NEXUS v1.0 | Powered by VirusTotal · Shodan · Censys · AbuseIPDB · NVD*
"""

print(report)
EOF
}

# Save recon output for embedding
echo "$RECON_OUTPUT" > /tmp/nexus_recon.txt
MARKDOWN=$(build_markdown)
MD_FILE="$REPORT_DIR/${REPORT_SLUG}.md"
echo "$MARKDOWN" > "$MD_FILE"
echo "✅ Markdown report: $MD_FILE"

# ── Obsidian Export ────────────────────────────────────────────
obsidian_export() {
  THREAT_INTEL_DIR="$OBSIDIAN_VAULT/Threat Intel"
  mkdir -p "$THREAT_INTEL_DIR"

  # Add Obsidian-specific frontmatter
  python3 - <<EOF > "$THREAT_INTEL_DIR/${REPORT_SLUG}.md"
import json, datetime

score_data = json.load(open('/tmp/nexus_score.json'))
md = open('$MD_FILE').read()

frontmatter = f"""---
target: "$TARGET"
date: "$(date '+%Y-%m-%d')"
score: $SCORE
risk: "$RISK"
tags: [nexus, osint, threat-intel, $RISK]
aliases: ["$TARGET recon", "$TARGET threat intel"]
---

"""
print(frontmatter + md)
EOF

  echo "✅ Obsidian note: $THREAT_INTEL_DIR/${REPORT_SLUG}.md"

  # Create/update index note
  INDEX="$THREAT_INTEL_DIR/00_Index.md"
  if [ ! -f "$INDEX" ]; then
    echo "# NEXUS Threat Intel Index" > "$INDEX"
    echo "" >> "$INDEX"
    echo "| Target | Date | Score | Risk |" >> "$INDEX"
    echo "|--------|------|-------|------|" >> "$INDEX"
  fi
  echo "| [[$REPORT_SLUG]] | $(date '+%Y-%m-%d') | $SCORE | $RISK |" >> "$INDEX"
  echo "✅ Updated Obsidian index"
}

# ── Notion Export ──────────────────────────────────────────────
notion_export() {
  if [ -z "$NOTION_TOKEN" ] || [ -z "$NOTION_DB_ID" ]; then
    echo "❌ NOTION_API_TOKEN or NOTION_DATABASE_ID not set in ~/.openclaw/.env"
    return 1
  fi

  echo "📤 Pushing to Notion..."

  # Convert markdown to Notion blocks
  python3 - <<'PYEOF'
import json, requests, os

token   = os.environ.get('NOTION_API_TOKEN')
db_id   = os.environ.get('NOTION_DATABASE_ID')
target  = "$TARGET"
score   = float($SCORE)
risk    = "$RISK"
ts      = "$TIMESTAMP"

headers = {
    "Authorization": f"Bearer {token}",
    "Content-Type": "application/json",
    "Notion-Version": "2022-06-28"
}

risk_color = {
    'CRITICAL': 'red', 'HIGH': 'orange',
    'MEDIUM': 'yellow', 'LOW': 'yellow', 'CLEAN': 'green'
}.get(risk, 'default')

score_data = json.load(open('/tmp/nexus_score.json'))
bd = score_data['breakdown']

def text_block(content, bold=False):
    return {
        "object": "block", "type": "paragraph",
        "paragraph": {"rich_text": [{"type": "text", "text": {"content": content},
                                      "annotations": {"bold": bold}}]}
    }

def heading(content, level=2):
    t = f"heading_{level}"
    return {"object": "block", "type": t, t: {"rich_text": [{"type": "text", "text": {"content": content}}]}}

def divider():
    return {"object": "block", "type": "divider", "divider": {}}

def table_row(cells):
    return {"cells": [[{"type": "text", "text": {"content": str(c)}}] for c in cells]}

blocks = [
    heading(f"Threat Report: {target}", 1),
    text_block(f"Generated: {ts}  |  Risk: {risk}  |  Score: {score}/100", bold=True),
    divider(),
    heading("Score Breakdown"),
    {
        "object": "block", "type": "table",
        "table": {
            "table_width": 3,
            "has_column_header": True,
            "has_row_header": False,
            "children": [
                table_row(["Source", "Score", "Detail"]),
                *[table_row([k.title(), f"{v.get('score',0)}/100", v.get('detail','')[:80]])
                  for k, v in bd.items()]
            ]
        }
    },
    divider(),
    heading("Recon Summary"),
    text_block(open('/tmp/nexus_recon.txt').read()[:1900] if os.path.exists('/tmp/nexus_recon.txt') else 'N/A'),
]

# Create page in database
page_payload = {
    "parent": {"database_id": db_id},
    "icon": {"type": "emoji", "emoji": "🎯"},
    "properties": {
        "Name":   {"title":  [{"text": {"content": f"[{risk}] {target}"}}]},
        "Target": {"rich_text": [{"text": {"content": target}}]},
        "Score":  {"number": score},
        "Risk":   {"select": {"name": risk, "color": risk_color}},
        "Date":   {"date": {"start": ts[:10]}}
    },
    "children": blocks
}

resp = requests.post(
    "https://api.notion.com/v1/pages",
    headers=headers,
    json=page_payload
)

if resp.status_code == 200:
    page_url = resp.json().get('url','')
    print(f"✅ Notion page created: {page_url}")
else:
    print(f"❌ Notion error {resp.status_code}: {resp.text[:200]}")
PYEOF
}

# ── Dispatch ───────────────────────────────────────────────────
case "$MODE" in
  --notion)   notion_export ;;
  --obsidian) obsidian_export ;;
  --all)
    obsidian_export
    notion_export
    ;;
esac

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Report complete: $TARGET  [$RISK $SCORE/100]"
echo "📁 Markdown : $MD_FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
